### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by prestonvanloon** [sourcegraph/sourcegraph-extension-docs#2]
This repo only as a README.md and a single tutorial. Where are the API docs?

**Comment by emidoots** [comment]
Hi -- currently there isn't an API docs / reference, this is issue https://github.com/sourcegraph/sourcegraph-extension-api/issues/46

The best place to get started is: https://github.com/sourcegraph/sourcegraph-extension-api#authoring-extensions

For the actual API, see https://github.com/sourcegraph/sourcegraph-extension-api/blob/master/src/sourcegraph.d.ts for now.

I'll close this in favor of https://github.com/sourcegraph/sourcegraph-extension-api/issues/46 -- hope that's okay!
